### PR TITLE
Registration details and ticket form.

### PR DESCRIPTION
**Pull request by ntoll**
**DO NOT MERGE THIS UNTIL WE HAVE AGREED / FINALIZED DETAILS AND I'VE SET UP THE CONFERENCE MEAL TICKET!**

This branch adds two changes:
- Information about registration.
- An embedded registration / ticket ordering form.

THIS NEEDS CHECKING BY SOMEONE WHO CAN BUILD THE SITE.

### CODE REVIEW

**Comment by inglesp** [comment]
Looks like we're successfully calling out to tito, but we may have the wrong event...

**Comment by inglesp** [comment]
screen shot 2015-04-16 at 15 05 26

**Comment by ntoll** [comment]
Bollocks... let me fix that. ;-)

**Comment by ntoll** [comment]
OK... can we ensure that styling is appropriate. I assumed the form "would just work" (tm) but the screenie from Peter suggests otherwise. It should look like the form here: https://ti.to/docs/widget

**Comment by ntoll** [comment]
OK... I just found the CSS file. :-/ I AM AN IDIOT x 2

**Comment by ntoll** [comment]
OK... should be good to go. Please check the CSS and tickets... ;-)

**Comment by inglesp** [comment]
Looks good to me.

**Comment by ntoll** [comment]
Screenie..? ;-)

**Comment by inglesp** [comment]
screen shot 2015-04-16 at 15 21 33

**Comment by ntoll** [comment]
Hmm... the width is off. The price should be on the same line as the x [0] elements. :-(

**Comment by inglesp** [comment]
Looks like this is caused by the amount of text in the description for the community ticket.

I don't have time to play around with this now, but we can look at this later.

**Comment by ntoll** [comment]
+1

AFAICT we just need to make some `tito-foo` class !important in some of our custom CSS (see https://ti.to/docs/widget)

**Comment by ntoll** [comment]
OK... I've updated the CSS and added a comment about correct CSS editing to the README... please check it works for you. ;-)

**Comment by ntoll** [comment]
I believe this is ready to merge! Yay.

Given I created the pull request can someone else do it..?

**Pull request merged**
