### PR TITLE
Add the schedule to the header.

### PR DESCRIPTION
**Pull request by zeth**
Would make sense to pull https://github.com/PyconUK/pyconuk.github.io/pull/41 first of course.

### CODE REVIEW

**Comment by inglesp** [comment]
The "Talks" tab will be replaced by "Programme" once #30 is merged.

I suggest we replace the CFP page with the schedule under the "Programme" tab once we've got the programme filled out, and not before.

@zeth did make the point elsewhere though that people are more likely to book if they know roughly what's happening on which days, so we should add that somewhere.  I've created #43 to track this.

@zeth -- happy for me to close this PR?

**Comment by zeth** [comment]
No to closing, I want the outline schedule before launch otherwise we risk people not booking hotels and trains for friday and monday (especially monday).

Just make two tabs or fit it together somehow.

Too much is unmerged, it didn't even know this existed when I was writing the other page.

**Comment by zeth** [comment]
Just have a Call for Participation and a Schedule tab. There are some forms of participation that do not time out (helping out, lightning talks, being on the reserve talk list etc)

**Comment by zeth** [comment]
This is outdated.

**Pull request closed without merging**
