### PR TITLE
Add code of conduct to static site...

### PR DESCRIPTION
**Pull request by ntoll**
This branch introduces two changes:
1. I've added copy of the code of conduct so I have somewhere that's not a wiki I can link to from the ticket booking form (attendees should tick a check box to say they have read, understood and agree to abide by the CoC as part of the ticket booking process).
2. I've updated the _config.yml file so the URL is for our pyconuk.org website.

### CODE REVIEW

**Comment by doismellburning** [comment]
<3

Will have a poke at errors, apologies

**Comment by doismellburning** [comment]
Yeah, another example of https://github.com/gjtorikian/html-proofer/issues/170 alas

Check out https://github.com/PyconUK/pyconuk.github.io/pull/20 - that should fix this

**Comment by inglesp** [comment]
@doismellburning I've merged #20 and have triggered another build of this PR (it didn't seem to be happening automatically, but maybe I was just being impatient) but it's failed, I think for the same reasons.

I'm going to merge this now because the build is failing for spurious reasons.

**Comment by doismellburning** [comment]
It failed for the same reasons, because, though #20 was merged, this PR didn't include it.

Ideally either @ntoll would have then merged `master` into his branch, or we'd have created a new PR and cherry-picked his commits into that - would you mind if we did that in future please? Cheers

**Pull request merged**
