### PR TITLE
Jekyll to wok

### PR DESCRIPTION
**Pull request by inglesp**
### Please do not merge

This Pull Request changes the static site generator from Jekyll to [wok](http://wok.mythmon.com/), which is Python-based.  It turns out it that this was less than an hour's work[0].  The changes to the workflow are described in the new README.

The main motivator for this has been that both @snim2 and @ntoll have been frustrated by the current tool chain in the past day.  While these changes won't prevent tool chain problems in the future, we should now have fewer moving parts, and those moving parts should be more familiar.

A second benefit to the change is that we can use reStructuredText directly, instead of HTML, which should simplify the schedule, at least.

A third benefit is that we can now say we're Python Powered -- I'm not fussed about this personally, but it might reduce some of the grousing on the mailing list!

This is not yet ready for merging, since I would like several people to test that the new workflow works, and that nothing has been lost in the migration.  I've tried to split the changes into meaningful chunks for review (hint: you can suppress whitespace in diffs on GitHub by appending `?w=1` to a url).

Finally, there's going to be a bit of git branch juggling to ensure that GitHub serves the content of the new output directory.  I'm going to follow [these notes](https://gist.github.com/cobyism/4730490) and will do a dry run with another site, but I can't guarantee that there won't be any down time for the site.  I will endeavour to do this sober.

Eating stilton and drinking Malbec'ly yours,

Peter.

[0] Getting the link checker to work properly is where my evening has actually gone, and it still doesn't work yet.  When it does, we can remove the Ruby-based link checker from the Travis checks, and be happy.

### CODE REVIEW

**Comment by ghickman** [comment]
@inglesp – this looks great, thanks for putting in the time!

A few things from looking at the diff:
- I've found wrapping basic commands in a `Makefile` very useful - they're tab completable and a little bit of help text goes a long way. I typically start with a `setup` (make sure virtualenv exists, pip things, etc) and `run` (do whatever is necessary for running the project).
- Could we have a requirements.txt please?
- I'm not sure I see the point in the `media` directory? It seems to just be another level above the `static` folder and the favicon? We could put the favicon in the `img` directory and save some drilling down =)

**Comment by inglesp** [comment]
Thanks @ghickman.
- I've added a `Makefile`.
- There's already a `requirements.txt`.
- wok uses the `media` directory for storing files that it doesn't need to process, so I just moved the original `static` directory inside it.  I'm sure we could do some rejigging here at a later point.

**Comment by ntoll** [comment]
This is a great start. Obviously there is much to do. I think we all owe @inglesp a pint at Pycon. ;-)

**Comment by ghickman** [comment]
@ntoll – :+1: 

@inglesp – oops, sorry I missed the requirements.txt in the diff stat!

**Comment by snim2** [comment]
I'm really impressed you did this so fast, thanks!

Build and serve works fine on my machine with your Makefile, except the Registration page [http://localhost:8000/register/] goes to a 404.

I have an new commit to add to this PR, can I push it to your PR branch? I couldn't figure this out from the GitHub docs :(

**Comment by inglesp** [comment]
@snim2: Well spotted, thanks!  I think that you should be able to make a pull request against the jekyll-to-wok branch in my repo, but you wouldn't be able to push to that branch.  Does that make sense?

@ntoll: Can you expand on "much to do"?

**Comment by snim2** [comment]
@inglesp I _think_ I've sent you a PR to the right place, hopefully.

We all owe you a good Merlot :+1:

**Comment by ntoll** [comment]
@inglesp it was only based on your "it's not ready to merge" comments. I have no doubt it's awesome code. ;-)

**Comment by ntoll** [comment]
Also, Stilton++ ;-)

**Comment by inglesp** [comment]
Closing, since work is now happening at https://github.com/PyconUK/pyconuk.org.

**Pull request closed without merging**
