### PR TITLE
Ignore this

### PR DESCRIPTION
**Pull request by zeth**
New blank schedule, rebased to maser. Still needs CSS to be perfect but more important to get  some kind of blank schedule up so people can book trains and hotels. Also the CSS will probably not be in this file but in an include, and probably won't be written by me. Also this page is no worse than some of the pages already live (e.g. /talks).

### CODE REVIEW

**Comment by ntoll** [comment]
Zeth, instructions on how to do CSS are at the bottom of the README. ;-)

**Comment by ntoll** [comment]
Initial comment about the timetable.

The education track needs fleshing out (something for me and the other edu-track people to do). But in the first instance there will be two tracks on the Friday: Teacher CPD and DjangoGirls. On the Saturday the whole place will be taken over for the kids. On the Sunday you could have two tracks for workshops.

Hope this helps,

Nicholas.

**Comment by ntoll** [comment]
Also, on the Saturday afternoon at around 3:30pm can we take over the main hall for kids show and tell (basically a 30minute mini-lightning talk session, perhaps with lightningtalkman hosting)..? Also, there appear to be no coffee/tea breaks. Surely we need at least 20 mins in both morning and afternoon for that..? Finally, the opening plenary on day 1 is 1 HOUR!!! Blimey... Surely we can move the keynote forward by 30 mins..?

**Comment by zeth** [comment]
Yes I was wondering about kids show and tell, that is a wonderful idea.

**Comment by ntoll** [comment]
Yay! The important thing is that they become part of the main conference. ;-)

**Comment by zeth** [comment]
These things are probably best done once the blank schedule is in? Otherwise I have to rebase the whole thing again and again.

**Comment by ntoll** [comment]
Perhaps I'm misunderstanding the purpose of this task then. I thought it was so we had a blank timetable for the whole conference, including all rooms and timings and we merely had to fill in the <td>'s with the appropriate talks and activities. If so, I would certainly like to see when the breaks are happening 'cos I'd put all the _heavy_ subjects just before them so people have chance to freshen up afterwards. ;-)

**Comment by ntoll** [comment]
Oops... I accidentally replace the words "table cells" with ' ;-)

**Comment by zeth** [comment]
Primary aim:
- Anecdotal experience shows that if we have a/any blank timetable up then people are more likely to come on Friday and Monday and to get correct train times.

Secondary aim:
- I want to use this to collaborate in making the schedule.

I know how to make a pull request from master, which I have done (twice). Once that is merged I can make more pull requests from master. Lots of them e.g. make those changes you have already proposed here, and keep changing it throughtout the buildup and during the conference.

However, until one version of the schedule is in, I cannot do that as you have exhausted how much I know and care about github and ruby based web frameworks. I don't know how to make pull requests of a pull request and if I have to rebase the whole github repo and type 10-20 shell commands just to update one cell in the schedule then I'll go back to using moinmoin.

**Comment by ntoll** [comment]
:-)

Yay Git.

So all you need to do is make whatever changes you need on `zeth:master` and they will automagically be propagated to this pull request. The whole point of PR's is that you can change them as you go along as people check them and provide helpful feedback etc... (which is what I'm trying to do). Once the reviewers are happy _they_ will merge your PR (i.e. not the author of the PR).

Also, you should really create a new branch for each feature you implement. So, for example, instead of doing all this on the `zeth:master` branch, you should `git checkout -b blank-timetable` to create and switch to a new branch called `blank-timetable`, then `git push origin blank-timetable` to push your changes to GitHub (and then create a new PR for that branch). It just helps keeps things clean and simple. 

This is also all explained in the README and was discussed on the mailing list and at one of the IRC meetings. :-)

**Comment by ntoll** [comment]
Happy to answer any and all GIT / GitHub related questions.

**Comment by zeth** [comment]
Not sure 'simple' is the word, but I will give it one more go. So are you saying I must delete the fork again, fork from master, make the branch and then make a new pull request?

**Comment by zeth** [comment]
Tea breaks make a congestion problem. Aim is to have the key and coffee available throughout the conference. Will make that clear to delegates in opening.

**Comment by ntoll** [comment]
:-)

Trust me, where GIT is concerned this is the simplest way and we're only following standard practice when it comes to working via GitHub.

I'm saying that your fork is fine. You just need to create a new branch in _your_ fork (`git checkout -b blank-timetable`) make your changes and create a new PR when you're done (`git push origin blank-timetable`). You probably want to add the main `pyconuk.github.io` repos as an "upstream" remote too (`git remote add upstream git@github.com:PyconUK/pyconuk.github.io.git` - off the top of my head) and then `git pull upstream master` to get the latest changes into your fork from the main repos.

Make sense..? ;-)

**Comment by zeth** [comment]
Opening plenary is generous but we often have problems starting on time (registration queue, AV mess-ups, crew disappearing to deal with a mini-crisis etc), keen to keep main timetable on track. Also we want some tribute to JP which will take a mo.

**Comment by zeth** [comment]
Possibly don't need teachers to come for any/all of opening plenary.

**Comment by ntoll** [comment]
OK... good point about tea breaks. When it comes to the Saturday kids day it would be good to have a couple of specified "break time" moments at, say, 11 and 2:30. Feedback from parents was that kids got hungry / thirsty.

Also, would be good to have teachers come to plenary. They are part of the community too. :-)

**Comment by zeth** [comment]
Yeah obviously kids/teachers track put in whatever breaks you like into the timetable.

**Comment by zeth** [comment]
Okay that seemed to break, I try again.

**Comment by zeth** [comment]
git clone https://github.com/zeth/pyconuk.github.io.git
cd pyconuk.github.io
git checkout -b timetable
mkdir schedule
cp ../pyconuk.github.io.2/schedule/index.html schedule/
git add schedule/index.html
git commit
git push origin timetable

Maybe this one worked.

**Comment by zeth** [comment]
Ends up in new one, https://github.com/PyconUK/pyconuk.github.io/pull/41

**Pull request closed without merging**
