### PR TITLE
Beginning of the schedule.

### PR DESCRIPTION
**Pull request by zeth**
Created and Edited using Emacs Table Mode (other tools can do this also, or you can
just line up the cells yourself in a text editor) which outputs a RST/Markdown table,
this is then run through the docutils command rst2html to make the HTML file.

Edits made directly to the HTML will be lost when someone generates a new schedule.

### CODE REVIEW

**Comment by zeth** [comment]
What time do you want the teacher's lunch, I might as well put that in.

**Comment by ntoll** [comment]
OK... I didn't realise this was automagically generated from something -> HTML.

Now that we have the bare bones what do you think of just editing the HTML directly (i.e. using a technology _everyone_ is familiar with). 

Regarding education track lunches on the Friday, they should be at the same time and place as everyone else.

For the kids we should have: 
- 11am "break" with fruit juice and biscuits (+ tea/coffee for parents), 
- 12:30pm lunch (a brown bag for each kid containing sandwiches, fruit, juice and packet of crisps), 
- 2:30pm "break" just like the 11am break.

Make sense..?

**Comment by ntoll** [comment]
Also, we probably don't need the "Simulation Centre" for the sprints. In fact, I believe that we only used the main hall and other room round the back of it during the sprints last year.

Sorry for being picky... just jotting things down as they occur to me.

**Comment by zeth** [comment]
"OK... I didn't realise this was automagically generated from something -> HTML."

Yes from a fairly standardized format of ascii text table, anyone can edit that in their own editor. You can even import and export it and from Excel if you are so inclined.

"Now that we have the bare bones what do you think of just editing the HTML directly (i.e. using a technology everyone is familiar with)."

A lot of people are familiar with docutils (I hope). Doing it in HTML takes forever, the tools that convert the table take care of all the details.  If you look at the Jan minutes of the IRC (and possibly many of the following ones), you will see I have been saying for many months that I will do the schedule this way.

If you are going to go down that line of telling me what to use, then why not make the site in Sphinx or plain github pages, both of which can take the table and convert it, Sphinx is the standard thing to use as a Python dev. Note this ruby thing probably can too, I just haven't looked into it yet.

**Comment by zeth** [comment]
"Also, we probably don't need the "Simulation Centre" for the sprints. In fact, I believe that we only used the main hall and other room round the back of it during the sprints last year."

Yep, thats right, sprints all together in one/two rooms. Just makes the table easier to have them as columns that can be filled in when the sprints are announced.

**Comment by zeth** [comment]
"Regarding education track lunches on the Friday, they should be at the same time and place as everyone else."

Cool, everyone else will have their lunch from 12-2, so whoever (you? Alan) is designing the Teacher track timetable can decide when to break lunch.

**Comment by zeth** [comment]
A cursory glance at the google results for jekyll and restructured text seems to give multiple ways to do this. So on a rainy day I (or someone) can make jekyll automatically create index.html from the schedule.rst file. Which will be useful for rapidly swapping out no-shows during the conference as we always do.

**Comment by zeth** [comment]
I put PyKids UK in the schedule, is there already an existing name? Pythonauts? RaspberryKids CodeSquash?

**Comment by snim2** [comment]
I don't understand these files or how you have edited them, and I didn't realise you put something about the Science Track until I just looked. 

Can you please tell me what you put for the Science Track and  how to edit what you put for the science track? Do I now have to edit BOTH the RST and the HTML? I won't be able to get to it until this afternoon, but I'll try to find time to sort something out after classes.

**Comment by ghickman** [comment]
> A lot of people are familiar with docutils (I hope).

This number will always be less than HTML.

> Doing it in HTML takes forever

Agreed, but lets use the lowest common denominator until the tooling is there so everyone can contribute.

> the tools that convert the table take care of all the details.

These tools don't exist for this repo _yet_.

> If you look at the Jan minutes of the IRC (and possibly many of the following ones), you will see I have been saying for many months that I will do the schedule this way.

Fantastic news! The rst file is clearly a better way to do this.

@zeth – I want to address this directly without derailing the issue at hand. Until we have the tooling in place to convert RST tables to HTML then we should be working with HTML. I agree it's not pretty, it's tedious _and_ we'll need to rebuild the tables when we do move over but it allows collaboration which is paramount to avoid low bus factor.

Please note - I _do_ agree that RST tables are better! We just need the tooling to deal with them so thank you for raising #45 and lets get that integrated to save everyone from the nightmare of HTML tables =)

**Comment by zeth** [comment]
At the moment, people can just put what changes they want in a github ticket and I will happily change them.

@ghickman 

"Agreed, but lets use the lowest common denominator until the tooling is there so everyone can contribute." 

Nope. I am using RST for the schedule as agreed in Jan and further meetings, thanks. I already compromised on using github pages then we didn't even use Sphinx or plain github pages which already support what I said needed. If you cannot wait for me or someone to setup the RST Jekyll plugin then there are lots of other parts of the site that need love. 

At the moment, people can just put what changes they want in a ticket github and I will happily change them, if they don't want to use rst2html. At the moment we do not have any talks to add so there is very limited amount of changes needed.  There is a limited amount of times I want to repeat the same argument that I want people to see the outline (empty) schedule so they can book their trains and hotels correctly.

**Comment by zeth** [comment]
@snim2 The schedule is made in schedule.rst which then gets run through rst2html to make index.html. you don't edit HTML directly. If someone merges the pull it (which I would have thought is really not a big deal as linking it up to the navigation is not in this pull request, so no one but us can actually see it) or you check out the branch then you can see it in jekyl. 

The abstracts page is just a basic Jekyll HTML page: https://github.com/zeth/pyconuk.github.io/blob/timetable/schedule/abstracts/index.html

When someone finally merges this version I will put the time in looking at the Jekyll RST plugin so that manually calling rst2html is not needed.

Seems that I committed the new index.html but schedule.rst seems to be one version behind, apologies, I will fix that when I get back to the house tonight.

**Comment by zeth** [comment]
"I agree it's not pretty, it's tedious and we'll need to rebuild the tables when we do move over but it allows collaboration which is paramount to avoid low bus factor."

If I get hit by a bus in the next week then I hereby certify that you can fork the HTML and edit it.

**Comment by ntoll** [comment]
+1 to increasing the bus number and doing the right thing **without needing certification from anyone**. Effective collaboration, cooperation and consensus wins _every time_.

:-)

grace1
grace2

**Comment by inglesp** [comment]
It's great that we're planning this sooner this year!  I think we should aim to know how many talks and workshops we can host before we start selecting them.

As for this PR, it looks good, but I don't think it's ready to merge yet.  A handful of things:
- Half an hour at the start of the Friday won't be enough time for registration.  Can we start registration at 8am?
- Alternatively, does the opening plenary need to be an hour long?  I don't remember it ever taking that much time before.
- One of the most common bits of feedback from last year was that we didn't leave enough time between talks for people to move between rooms, and that changeovers were often rushd. Last year, most talks were 30 minutes including questions, and we've got the same pattern on the CFP this year (although that can be changed, if we decide soon).  So I think we should space the talk sessions to be 40 minutes apart.
- There's no space for workshops.  If last year's anything to go on, we might expect to have one room dedicated to workshops.
- It's not clear when lunch is -- I presume that's what the W1/W2/etcs are, but it'd be good to be clear.
- Do we need to leave space for DjangoGirls?  For Trans*Code?  Do we know what days these are happening on yet?

Finally, I'm not too excited about how we convert the .rst in .html, as long as there are clear instructions somewhere.

**Comment by snim2** [comment]
- Please add a column to the Saturday and Sunday schedules specifically for the Science Track. You could name the room after the sponsor who will be paying for it (i.e. "The Software Sustainability Institute Room" or "The Software Sustainability Room").
- The SSI room should be hosting tutorials (1//2 day each) on Saturday and talks (40 mins each) on Sunday. Hopefully at least one of the Plenary talks on Sat / Sun will be science related, so the science people will probably go to both.
- On the Sprint day you also need a column for the Science Track, this could either be in the SSI room or in part of the main room. The text for the Science column (repeated in morning and afternoon slots) should say the following:

collaborative <strong>open science sprint</strong> where you can bring along a task to automate, or a piece of code you want to open source, and we will put you in groups to turn your existing scripts or workflow into an reproducible piece of open science! Watch this space -- there may be prizes :)
- Please also change this text in the abstract page:

<h2>Python for Science</h2>

<p>The Python for Science events will be published in the run up to the conference.</p>

To this:

<h2>Python for Science</h2>

<p>
If you are a working scientist then this track is for you -- whether you have never used Python before and want to dip your toe in the water, or you are a fully-fledged Pythonista, looking to expand your repertoire. The PyConUK Science Track will offer you three days of learning, collaboration and fun, and a chance to meet other scientists using Python.
</p>

<p>The PyConUK Science Track will feature:
<ul>
<li>tutorials on Python suitable for beginner Python programmers where you can learn to automate common data analysis and visualisation tasks</li>
<li>talks from other scientists and professional software engineers on Python in science and best practices for developing your own code</li>
<li>a collaborative <strong>open science sprint</strong> where you can bring along a task to automate, or a piece of code you want to open source, and we will put you in groups to turn your existing scripts or workflow into an reproducible piece of open science!
Watch this space -- there may be prizes :)</li>
</p>

**Comment by zeth** [comment]
"without needing certification from anyone" - you mean like how I have been waiting three days to put a single HTML page on the site?

**Comment by zeth** [comment]
I am starting to get in a mess with 9 commits to the pull request. I will keep changing what people need here but future changes would be better as a new pull request. If someone agrees with 1-9 and 12 but disagrees with 10 and 11, it would be beyond my git knowledge to sort that out.

@inglesp  
- Half an hour at the start of the Friday won't be enough time for registration. Can we start registration at 8am?
- Alternatively, does the opening plenary need to be an hour long? I don't remember it ever taking that much time before.

We can maybe open registration at 8am, not really under my control, we would have to ask Mary or whoever is running the desk if they want to.

You are right it does not need to be an hour long (about 30 mins), it is a trick, intentional padding. It is about shepherding, people will get good train times and through registration and into the room early, but even if they don't there is enough space for things to go wrong (people not moving through registration fast enough, AV problems, critical crew member dealing with a minicrisis) without the main schedule starting late. So we won't really take an hour. Does that make any sense?
- One of the most common bits of feedback from last year was that we didn't leave enough time between talks for people to move between rooms, and that changeovers were often rushd. Last year, most talks were 30 minutes including questions, and we've got the same pattern on the CFP this year (although that can be changed, if we decide soon). So I think we should space the talk sessions to be 40 minutes apart.

Great idea I will make the schedule work like that.
- There's no space for workshops. If last year's anything to go on, we might expect to have one room dedicated to workshops. It's not clear when lunch is -- I presume that's what the W1/W2/etcs are, but it'd be good to be clear.

Workshops that are more than 1-2 hours we can schedule in the normal talk slots. There is no space given for those at the moment.

The W1 etc are placeholders for lunchtime workshops. The idea in general is explained on the mailing list before but the short version is that between 12 and 2 lunch will be available in the restaurant. Each delegate will be assigned a 30 min arrival slot (12:00 or 12:30 or 13:00) and hopefully a majority of people will roughly turn up at the right time. 

Workshops/talks/job fair/book launches/discussions/other things that seem suitable will be given the slots W1. I.e. workshops that are either less than an hour long and repeatable or can cope with people dropping in and out will be in lunch time. I will attempt to make this more clear on the schedule.

This way, people can go to their eating slot without missing anything and yet we don't need two blank hours in the schedule. Does this make any sense?
- Do we need to leave space for DjangoGirls? For Trans*Code? Do we know what days these are happening on yet?

I think someone (Nick?) said DjangoGirls started on Friday so I thought we have a column currently called room 4 (sponsored room names come lately obviously) to be theirs from 11:30 until they don't need it anymore, such as 18:30 if they go until the end of the day.
- For Trans*Code? Do we know what days these are happening on yet?

I don't, it would be good to find out.

**Comment by zeth** [comment]
@snim2 Thanks for the changes, I will add all those shortly.

**Comment by zeth** [comment]
Added the bit to the abstracts page.

I am very happy to make changes of course, but just a friendly note that page is just a normal HTML page so anyone can change it without using RST, although the git machinations required to change it before the first version is merged are another thing.

**Comment by zeth** [comment]
Sorry @snim2, one question it says "The PyConUK Science Track will offer you three days of learning, collaboration and fun", so I read that as you are doing it from Sat to Mon? You don't want a science schedule on Friday?

**Comment by snim2** [comment]
@zeth Sat->Mon is the plan, yes

**Comment by zeth** [comment]
Should Simulation Centre be Bank of America Simulation Centre?

**Comment by zeth** [comment]
@snim2 In the schedule I assumed Python for Science would break for keynotes/lighting talks etc. Is that true or you want me to change it so that the Py4Sci track powers on through it?

**Comment by zeth** [comment]
Another stupid question for @snim2  Are the general Python delegates who like science allowed to wander in and sit in on the Python for Science track or is only for people who registered as scientists?

**Comment by zeth** [comment]
@snim2 On the Friday, is one of the rooms still called the Software Sustainability Institute Room (albeit with non-specific content in)?

**Comment by ghickman** [comment]
> I am starting to get in a mess with 9 commits to the pull request. I will keep changing what people need here but future changes would be better as a new pull request. If someone agrees with 1-9 and 12 but disagrees with 10 and 11, it would be beyond my git knowledge to sort that out.

@zeth – no need to worry! If someone disagrees with commits 10 & 11 then push a 13th commit with new changes. This will update the final diff that this PR encapsulates (see the "[Files Changed](http://cl.ly/image/2Z2U160d3u3J/Image%202015-04-25%20at%2012.04.53%20am.png)" tab at the top of this page to see this in action based on your current commits).

On a side note I'm now in the #pyconuk IRC channel if anyone needs a hand with Git/GitHub stuff =)

**Comment by zeth** [comment]
@inglesp Re bigger talk slots, there seems to be two ways to do what you want, I can make them 30 min talk slots with a blank line between (i.e. the ten minute change over time becomes semi-explicit) or I can make the slots 40 mins big. Any preference?

**Comment by zeth** [comment]
40 min slots does weird things to the understand-ability of the time column but I am sure it will come out okay in the end.

**Comment by zeth** [comment]
Turns out understandability is not a real word, who knew!

**Comment by zeth** [comment]
Ah thanks @ghickman that is a much simpler way of looking at it!

**Comment by zeth** [comment]
@snim2 Okay I see the bit about plenaries and Science is answered earlier in this thread.

**Comment by zeth** [comment]
What does a nuclear physicist eat for lunch? Fission Chips

To go the keynote and to eat lunch means that Python for science on Saturday is split into three blobs.

**Comment by zeth** [comment]
@snim2 or you can make the scientists have lunch at 13:30 which means you get two blobs but in that case one is 10:30 to 13:30 and one is 16:00 to 17:30. Probably makes it worse.

**Comment by zeth** [comment]
Okay got everything someone asked for before the 40 min talk size revolution. The next change will be quite massive.

**Comment by ntoll** [comment]
It's great all this work is being done _now_. Being able to see the "shape" of the conference up-front is hugely useful IMO. :-)

However, there are couple of revisions to do with the education track details:
- Django Girls are part of the education track, not part of the software sustainability stuff. By this I mean there are two "tracks" of an educational nature in the Simulation Centre on the Friday: teacher CPD and Django Girls. (On the Saturday the whole SimCentre being set aside for the kids.)
- "Bank of America Education Track" is perhaps a better / more accurate name.
- The education track[s](like the Science track) should probably be mentioned in the abstracts page. However, rather than putting a bunch of text in the abstracts page, why not just link to both the education and science pages on the website..?

**Comment by snim2** [comment]
@zeth **In the schedule I assumed Python for Science would break for keynotes/lighting talks etc. Is that true or you want me to change it so that the Py4Sci track powers on through it?** Scientists should certainly be at the Keynotes, probably the lightening talks, maybe not the Panel. I guess this is something we can tweak later. At this point we don't know how many "Python Science" talk proposals we will get, so it's difficult to be really sure.

@zeth - **Are the general Python delegates who like science allowed to wander in and sit in on the Python for Science track or is only for people who registered as scientists?** -- if there is room, sure. I was expecting that we would make available as many tickets as there are seats in the SSI room. @ntoll will remember how many tickets we reserved.

@zeth **On the Friday, is one of the rooms still called the Software Sustainability Institute Room (albeit with non-specific content in)?** That's up to you. I wasn't expecting to pay for the room on Friday, but I can look at that if I have an estimate of the costs.

@zeth **or you can make the scientists have lunch at 13:30 which means you get two blobs but in that case one is 10:30 to 13:30 and one is 16:00 to 17:30. Probably makes it worse.** I'm not sure what you mean, but if the lunch really is going to be staggered then I guess you want the scientists and edu tracks to eat at slightly different times to the main track. On the other hand that seems like a shame because it offers less chances for a good corridor track. I'm not sure what the best answer is there. EP14 resolved it by serving lunch from several different locations, but I don't think the venue will offer us that.

**Comment by inglesp** [comment]
@zeth, thanks for the great job you're doing in pulling all the different scheduling requirements together!

What would you think about separating this PR into two: one that covers the schedule, and one that covers the programme (ie what's in abstracts/index.html)?

That way, we can make the programme public when we go launch the conference, and not be rushed into getting the schedule right.

**Comment by ntoll** [comment]
@snim2 wrt Friday room: AFAICT we have the whole conference centre so it's just a question of nominating a space. The simulation centre could help out in this regard: the downstairs room and upstairs room are for DjangoGirls and the Teachers CPD on Friday, but there is a third large space in the SC available that we can use. Would it be helpful for us to visit the place and work out the logistics..?

@inglesp +1 on two PRs... the water is getting very muddy here.

**Comment by nceder** [comment]
Presumably if we are doing Trans_Code, we'll want a space on Friday? My
thinking was that it would only be on the Friday, although the Django Girls
had suggested that having the Trans_Code hack day the after their workshop
would be nice - that way some of the newly trained people could
participate. Depends on the space/resources available.

Naomi

On 25 April 2015 at 10:03, Nicholas Tollervey notifications@github.com
wrote:

> @snim2 https://github.com/snim2 wrt Friday room: AFAICT we have the
> whole conference centre so it's just a question of nominating a space. The
> simulation centre could help out in this regard: the downstairs room and
> upstairs room are for DjangoGirls and the Teachers CPD on Friday, but there
> is a third large space in the SC available that we can use. Would it be
> helpful for us to visit the place and work out the logistics..?
> 
> @inglesp https://github.com/inglesp +1 on two PRs... the water is
> getting very muddy here.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyconUK/pyconuk.github.io/pull/41#issuecomment-96162954
> .

## 

Naomi Ceder
https://plus.google.com/u/0/111396744045017339164/about

**Comment by ntoll** [comment]
@nceder absolutely... apologies for my complete lack of "having a clue". :-/

I guess it would be useful if we have agreed and written down somewhere what both Trans*Code and Django Girls have in mind for the Friday. In some dusty corner of my mind I seem to remember an agreement between TC and DG to collaborate/cooperate - although it's highly likely that I'm imagining this.

**Comment by nceder** [comment]
You're quite right about the agreement, the thing is we hadn't worked out a
ton of details. As I see it (and I would want to confirm this with Olivia
and Rina) what we talked about was:
1. Django Girls on Friday, with capacity X (I don't remember the exact
   number), with some special outreach/accommodation to the trans\* community.
2. Trans*Code Hackday for ~30 people with some special
   outreach/accommodation to Django Girls/PyLadies (i.e., Django Girls who've
   already completed the workshop)
3. Their (Django Girls orgs) suggestion was that having the hack the day
   after their workshop would let those people choose to participate. My
   assumption was that there wouldn't be space on the Saturday, since the kids
   day really fills things up.

At this point I don't think we have anything more worked out than that.

On 25 April 2015 at 10:29, Nicholas Tollervey notifications@github.com
wrote:

> @nceder https://github.com/nceder absolutely... apologies for my
> complete lack of "having a clue". :-/
> 
> I guess it would be useful if we have agreed and written down somewhere
> what both Trans*Code and Django Girls have in mind for the Friday. In some
> dusty corner of my mind I seem to remember an agreement between TC and DG
> to collaborate/cooperate - although it's highly likely that I'm imagining
> this.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyconUK/pyconuk.github.io/pull/41#issuecomment-96168657
> .

## 

Naomi Ceder
https://plus.google.com/u/0/111396744045017339164/about

**Comment by ntoll** [comment]
@nceder ok... all understood.

I suggest we take this discussion away from the PR and try to organise with DG so we have a firm plan. I'm happy to meet up with people in London next week if need be or do an appear.in. I'll ping out an email right now.

**Comment by zeth** [comment]
@zeth On the Friday, is one of the rooms still called the Software Sustainability Institute Room (albeit with non-specific content in)? That's up to you. I wasn't expecting to pay for the room on Friday, but I can look at that if I have an estimate of the costs.

The room on Friday can be called something else, that is not a problem, I just didn't know how the SSI sponsorship and room sponsorship intersected.

**Comment by snim2** [comment]
@zeth good point, I just checked my spreadsheet, which tells me I costed out the price of a room `* 3`. So I guess you could take that as paying for the room Fri->Sun and then using part of the main room on Mon (if you think there will be space) or you could take it as using no rooms on Friday and using the room Sat->Mon. I don't especially mind either way.

**Comment by zeth** [comment]
At the moment, the quickest way to see the latest schedule in my branch is to look here:
https://github.com/zeth/pyconuk.github.io/blob/timetable/schedule/schedule.rst

Currently this does not include changes ask for today, it will after I finish the conversion to 3/4 time. 

Since we have a wealth of special tracks we should try to use that to help stagger the lunches in a more natural fashion.

**Comment by zeth** [comment]
@zeth - Are the general Python delegates who like science allowed to wander in and sit in on the Python for Science track or is only for people who registered as scientists? -- if there is room, sure. I was expecting that we would make available as many tickets as there are seats in the SSI room. @ntoll will remember how many tickets we reserved.

Are the rooms pre-assigned. If not then why not put in a bigger room? I expect the talks will be quite popular among the general delegates, firstly because there are a lot of people with some science interest (such as science first degrees, experience doing coding in science-based industry, etc etc) who will want to see and it is something different than previous years will guarantee interest. If someone wants to bet a beer against me, I reckon there will be at least 50 general delegates who want to watch the science track, maybe more.

**Comment by zeth** [comment]
Sorry forgot to put @snim in the last comment.

**Comment by zeth** [comment]
I forgot to put @snim2 in the last comment. Grrrr

**Comment by zeth** [comment]
Thread is getting a bit long, I have assigned the outstanding requested tasks to myself in issues. Please assign me changes there so I don't lose them, especially ones that require someone else to do or figure out something first.

**Comment by snim2** [comment]
@zeth I'm fine with that, but someone needs to tell me how much the bigger room will cost, then when that is settled I can figure out how to move the money over.

**Comment by ntoll** [comment]
OK... I think this is good to merge but for one thing (the build instructions in the README...). I have no idea for how to turn the pretty ascii tables into HTML. ;-)

**Comment by zeth** [comment]
On 4 May 2015 at 20:42, Nicholas Tollervey notifications@github.com wrote:

> OK... I think this is good to merge but for one thing (the build
> instructions in the README...). I have no idea for how to turn the pretty
> ascii tables into HTML. ;-)

Well that is talked about in a github issue that is separate from this pull
request. It doesn't stop anyone merging this copy of the rendered output.
To see how the current rendered schedule looks, you just run Jekyll.

Anyway to repeat what we already discussed elsewhere, what we already
decided was to set up Jekyll up to do it automatically using the RST plugin
which is talked about elsewhere. Then we can do fast automated changes
during talk acceptance and during the conference.

I am hoping someone who likes Jekyll and Ruby will will fix this for me,
otherwise I do myself in time for hen Peter and Sarah have accepted all the
talks.

Until then (as a short term measure), you do what you just did, edit the
.rst. I then use the utility rst2html (command comes when you install
docutils) to get the html.

As explained elsewhere, as far as I understood the RST plugin, once it is
setup, no one can do the rst2html approach ever again as it will overwrite
the information in the HTML file which Jekyll needs. So I am wary of
checking in a bash script that does the deprecated approach in case that
someone accidentally nukes the schedule during the conference by using it.

Best Wishes,
Zeth

**Comment by zeth** [comment]
On 4 May 2015 at 22:09, Zeth theology@gmail.com wrote:

> hen Peter and Sarah have accepted all the talks.

str.replace('hen', 'when')

There is probably a rule against accidentally assigning farmyard
animals to organisers :) I think Peter is more of a lion anyway.

**Comment by snim2** [comment]
elsewhere == Issue #44, Issue #45, Issue #46 and this PR.

**Comment by inglesp** [comment]
I think this is good enough to merge.  There are a few minor tweaks I'd like to make are big enough as they are.

Thanks @zeth/@everyone for getting this done!

**Pull request merged**
