### PR TITLE
Launch updates

### PR DESCRIPTION
**Pull request by ntoll**
This branch introduces the following changes:
- The registration form (including links to TransCode/Django Girls expression of interest, and unwaged/student forms) is now live.
- I make it especially clear about the new meal tickets.
- The CfP is now live.
- The skeleton schedule is linked from the CfP page.
- I removed BAML references from the education track since it's not confirmed yet (we can change back when we know for certain).

I have noticed a few inconsistencies  between the CfP form and the skeleton schedule which I'll discuss with @inglesp.

### CODE REVIEW

**Comment by doismellburning** [comment]
@zeth You appear to have merged this despite the tests failing. Could you not, please?

**Comment by ntoll** [comment]
Bugger... that's my PR too... let me fix things on a new branch.

**Comment by nceder** [comment]
I do have one question about the notion of Trans*Code participants getting
a full conference ticket... we asked for support only for the day (see BAML
spreadsheet). So I'm not sure we have funding for full tickets. I also
don't know that every participant will want the full ticket. Maybe at the
least we change the wording to "is eligible for a free ticket" or something
like that?

Naomi

On 12 May 2015 at 12:21, Kristian Glass notifications@github.com wrote:

> @zeth https://github.com/zeth You appear to have merged this despite
> the tests failing. Could you not, please?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyconUK/pyconuk.github.io/pull/52#issuecomment-101243507
> .

## 

Naomi Ceder
https://plus.google.com/u/0/111396744045017339164/about

**Comment by ntoll** [comment]
@nceder good point... will change as appropriate

@doismellburning out of interest, is there some way to run the tests locally..? (I don't see anything in the README)

**Comment by ntoll** [comment]
@nceder hmm... I think the full ticket thing is only in the email template I sent out. Not in any of the changes here (afaict)

**Comment by nceder** [comment]
Ah, cool... that makes life easier - maybe that was what I was thinking of.

On 12 May 2015 at 12:26, Nicholas Tollervey notifications@github.com
wrote:

> @nceder https://github.com/nceder hmm... I think the full ticket thing
> is only in the email template I sent out. Not in any of the changes here
> (afaict)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyconUK/pyconuk.github.io/pull/52#issuecomment-101245194
> .

## 

Naomi Ceder
https://plus.google.com/u/0/111396744045017339164/about

**Comment by ntoll** [comment]
Hi... the failing tests are now addressed by PR #53 (basically, we had some old crufty templates left hanging around about the soon-to-be-retired wiki - they weren't even linked to from the main site.)

**Pull request merged**
