### PR TITLE
Jekyll

### PR DESCRIPTION
**Pull request by doismellburning**
Because I <3 templating

(YMMV)

### CODE REVIEW

**Comment by ntoll** [comment]
Hi Kristian,

Please add some sort of documentation!!! I've never used Jekyll and have no idea how to use it. A quick howto would be appreciated in the README.

N.

**Comment by ntoll** [comment]
Also.... Ruby..? Is there something in Python that we can use instead (for static site generation)...?

**Comment by ntoll** [comment]
In fact, upon thinking about it more, can we please back this out and at least try to find and check a Python alternative..? (I'm not saying NOT Jekyll, but I don't think it's the only choice and I'm uncomfortable that we're a Python community event and we're not dogfooding our language).

**Comment by ntoll** [comment]
Finally (sorry, it's too early for a Sunday morning), I also <3 templating. ;-)

**Comment by inglesp** [comment]
+1 to adding some documentation here!  It's important that anybody who wants to can build the site locally.

As for which static site generator we use, I can see the appeal of using something written in Python, but I don't think it's a requirement -- and "practicality beats purity"!  The advantage of Jekyll is that GitHub knows what to do with a site with Jekyll's structure, so there's no build stage required.  As far as I know, this isn't the case for other static site generators.

Thanks @doismellburning for doing the work here.

**Comment by doismellburning** [comment]
> Also.... Ruby..? Is there something in Python that we can use instead (for static site generation)...?

Yes; Pelican + Hyde. Last time I did an evaluation, they were inferior clones of Jekyll; this may not still be the case though.

As @inglesp says though, it'd involve having Travis (or equivalent) do the build, as GH pages won't automatically, plus then either migrating away from GH pages, or having hacks and sadness in Travis to force push the build results to the `gh-pages` branch. While I'm more than happy to configure this, pay for it, and maintain it, it would seem a suboptimal approach

> I'm uncomfortable that we're a Python community event and we're not dogfooding our language

I would prioritise suitability/utility over purity, and look forward to seeing you write [Brython](http://www.brython.info/) ;) &lt;/troll&gt;

(Seriously though: sure, but see above for why I wouldn't)

((Yes I _did_ hand-encode those HTML entities above, and yes I did manage to get them the wrong way round at first, sigh))

**Comment by doismellburning** [comment]
@ntoll See #13 (but, er, also #14 as a test-y-pass-y prereq)

**Comment by sparkslabs** [comment]
Seems a very bizarre choice to use ruby to drive a python conference website. Seems to suggest that python can't be used for this task, which isn't true. It's not like there aren't static site generators for python. Your site, your rules, but you're less likely to get python people interested in helping out with a ruby powered site. 
</tuppenceworth>

**Comment by ntoll** [comment]
So the problem I have is that a _fundamental aspect_ of how the website is built has been arbitrarily decided by a pull request (that was merged quite quickly). Personally, I believe this should have been suggested on the mailing list for all to have a say in - especially since the language of choice is Ruby and not Python.

**Comment by russel** [comment]
@ntoll @sparkslabs Having chosen to host the site at GitHub pages, the natural choice of system is Jekyll. Whilst it might be nice to use a Python-based system such as Nikola with AsciiDoc (or ReStructured Text), GitHub is a Markdown/HTML/Jekyll/Git workflow. The fact that it is Ruby underneath doesn't actually show and in a sense doesn't matter.

If the site must be driven with Python then GitHub pages is not really the right hosting place. I am not sure where is.

**Comment by sparkslabs** [comment]
No, github page _can_ be used without using Jekyll. The argument that you
_must_ use Jekyll to use github pages is bogus.

At the end of the day though, it's the decision for those willing to put
effort in, and I suspect I fall into the camp of "would like to have time
but don't" so I'll leave everyone else to it.

Michael.

**Comment by snim2** [comment]
Deploying Nikola to GitHub:

http://getnikola.com/handbook.html#deploying-to-github

(not an endorsement, I've never used Nikola!)

**Comment by russel** [comment]
@sparkslabs Indeed GitHub pages _can_ be used without Jekyll, it is that Jekyll is the path of least resistance to getting Markdown-based sources up as a website on GitHub pages.

@snim2 I use Nikola for my website (on advice from Simon Davy, who believes Nikola superior to Pelican) and it works well, I like it. There is this:  http://govlab.github.io/6109/posts/static-site-comparison-nikola-vs-pelican.html

Nikola works with AsciiDoc and ReStructuredText as well as Markdown. Indeed my site comprises files using all of them.

Given @ntoll position maybe switch from Jekyll to Nikola even though there is an extra overhead?

**Pull request merged**
